use_frameworks!

target 'iOS Demo' do
  platform :ios, '13.0'
  pod 'DropmarkSDK', :path => '../'

  target 'DropmarkSDK_Tests' do
    inherit! :search_paths
  end
  
end

target 'macOS Demo' do
    platform :osx, '10.12'
    pod 'DropmarkSDK', :path => '../'
end

target 'tvOS Demo' do
    platform :tvos, '13.0'
    pod 'DropmarkSDK', :path => '../'
end
