//
//  DKInvite.swift
//
//  Copyright © 2020 Oak, LLC (https://oak.is)
//
//  Permission is hereby granted, free of charge, to any person obtaining a copy
//  of this software and associated documentation files (the "Software"), to deal
//  in the Software without restriction, including without limitation the rights
//  to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
//  copies of the Software, and to permit persons to whom the Software is
//  furnished to do so, subject to the following conditions:
//
//  The above copyright notice and this permission notice shall be included in
//  all copies or substantial portions of the Software.
//
//  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
//  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
//  FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
//  AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
//  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
//  OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
//  THE SOFTWARE.
//

import Foundation

public final class DKInvite: NSObject, DKResponseObjectSerializable, DKResponseListSerializable {
    
    /// The unique identifier of the invite
    public var id: NSNumber
    
    
    public var name: String
    
    /// Not to be confused with the `NSObject` `description`, this is the Dropmark-defined description of an invite
    public var descriptionText: String?
    
    
    public var url: String
    
    public var shortURL: String
    
    /// The date the invite was created
    public var createdAt: Date
    
    /// The date the the invite was last updated
    public var updatedAt: Date?
    
    /// User-defined thumbnail image URL, if available
    public var thumbnail: String?
    
    /// A suite of thumbnails generated by Dropmark
    public var thumbnails: DKThumbnails?
    
    /// The creator of the invite
    public var user: DKUser?
    
    // MARK: DKResponseObjectSerializable
    
    /**
     
     Serializes a new instance from the provided network response and key-value representation. The representation is validated for the required parameters, then fills in optional parameters as necessary.
     
     - Parameters:
        - response: A network response assocated with serialization
        - representation: A key-value object representing parameters and child objects.
     
     */
    
    public required init?(response: HTTPURLResponse, representation: Any) {
        
        guard
            let representation = representation as? [String: Any],
            let id = representation["id"] as? NSNumber,
            let name = representation["name"] as? String,
            let url = representation["url"] as? String,
            let shortURL = representation["short_url"] as? String,
            let createdAtString = representation["created_at"] as? String,
            let createdAt = DKDateFormatter().date(from: createdAtString)
        else { return nil }
        
        self.id = id
        self.name = name
        thumbnail = representation["thumbnail"] as? String
        
        if let thumbnailsRepresentation = representation["thumbnails"]  {
            thumbnails = DKThumbnails(response: response, representation: thumbnailsRepresentation)
        }
        
        descriptionText = representation["description"] as? String
        self.createdAt = createdAt
        
        if let updatedAtString = representation["updated_at"] as? String {
            updatedAt = DKDateFormatter().date(from: updatedAtString)
        }
        
        if let userID = representation["user_id"] as? NSNumber {
            
            let user = DKUser(id: userID)
            user.name = representation["user_name"] as? String
            user.username = representation["username"] as? String
            user.email = representation["user_email"] as? String
            
            if let avatarString = representation["user_avatar"] as? String, let avatar = URL(string: avatarString) {
                user.avatar = avatar
            }
            
            self.user = user
            
        }
        
        self.url = url
        self.shortURL = shortURL
        
    }
    
}

/**
 
 Returns whether the two invites are equal.
 
 - Parameters:
     - lhs: The left-hand side value to compare.
     - rhs: The right-hand side value to compare.
 
 - Returns: `true` if the two values are equal, `false` otherwise.
 
 */

public func ==(lhs: DKInvite?, rhs: DKInvite?) -> Bool {
    return lhs?.id == rhs?.id
}
